namespace Prior_Authorization_Workflow_Tracker.Models;

/// <summary>
/// Core PA request entity (§7.1).
/// RowVersion is an EF Core optimistic concurrency token configured as IsRowVersion()
/// in AppDbContext (BUG-002 mitigation).
/// IsDeleted is subject to a global EF Core HasQueryFilter (BUG-003 mitigation).
/// </summary>
public class PaRequest
{
    public int ID { get; set; }

    /// <summary>Human-readable identifier, e.g. "PA-2026-00001". Generated by PaRequestService.</summary>
    public string RequestNumber { get; set; } = string.Empty;

    public string PatientMrn { get; set; } = string.Empty;

    public string PatientName { get; set; } = string.Empty;

    public DateTime PatientDob { get; set; }

    // ── Foreign keys ──────────────────────────────────────────────────────────

    public int InsurancePlanID { get; set; }

    /// <summary>FK to AspNetUsers; the clinician ordering the service.</summary>
    public string ProviderID { get; set; } = string.Empty;

    /// <summary>FK to AspNetUsers; the Authorization Specialist who created/submitted.</summary>
    public string SubmittedByUserID { get; set; } = string.Empty;

    public int ProcedureCodeID { get; set; }

    // ── Clinical fields ───────────────────────────────────────────────────────

    /// <summary>ICD-10 code; must match BR-003 regex: ^[A-Z][0-9]{2}(\.[0-9A-Z]{1,4})?$</summary>
    public string DiagnosisCode { get; set; } = string.Empty;

    /// <summary>Minimum 50 characters enforced by BR-010.</summary>
    public string ClinicalJustification { get; set; } = string.Empty;

    // ── Workflow ──────────────────────────────────────────────────────────────

    public PaStatus Status { get; set; } = PaStatus.Draft;

    public PaPriority Priority { get; set; } = PaPriority.Routine;

    /// <summary>Null while the request is in Draft. Set on first submission transition.</summary>
    public DateTime? SubmittedAt { get; set; }

    /// <summary>
    /// Calculated on submission: SubmittedAt + plan SLA days adjusted for Priority (BR-002).
    /// </summary>
    public DateTime? DecisionDueDate { get; set; }

    public DateTime? DecisionRenderedAt { get; set; }

    // ── Units ─────────────────────────────────────────────────────────────────

    /// <summary>BR-004: must be 1–999.</summary>
    public int ApprovedUnitsRequested { get; set; }

    /// <summary>BR-007: cannot exceed ApprovedUnitsRequested. BR-012: must be ≥ 1 if set.</summary>
    public int? ApprovedUnitsGranted { get; set; }

    // ── Approval fields ───────────────────────────────────────────────────────

    /// <summary>Format: "AUTH-YYYYMMDD-XXXXX". Generated by WorkflowService on approval.</summary>
    public string? AuthorizationNumber { get; set; }

    /// <summary>BR-011: must be ≥ current date at time of approval decision.</summary>
    public DateTime? AuthorizationStartDate { get; set; }

    /// <summary>BR-006: must be after AuthorizationStartDate.</summary>
    public DateTime? AuthorizationEndDate { get; set; }

    // ── Denial fields ─────────────────────────────────────────────────────────

    public int? DenialReasonID { get; set; }

    public string? DenialNotes { get; set; }

    // ── Reviewer ──────────────────────────────────────────────────────────────

    public string? ReviewerUserID { get; set; }

    // ── Audit ─────────────────────────────────────────────────────────────────

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Soft delete flag (BR-014). Active requests use IsDeleted = false.
    /// AppDbContext has a global HasQueryFilter so deleted rows are invisible to normal queries.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// EF Core optimistic concurrency token (rowversion / timestamp).
    /// Prevents simultaneous reviewer decisions (BUG-002 mitigation, §7.1).
    /// </summary>
    public byte[] RowVersion { get; set; } = [];

    // ── Navigation properties ─────────────────────────────────────────────────

    public InsurancePlan InsurancePlan { get; set; } = null!;
    public ApplicationUser Provider { get; set; } = null!;
    public ApplicationUser SubmittedByUser { get; set; } = null!;
    public ProcedureCode ProcedureCode { get; set; } = null!;
    public DenialReason? DenialReason { get; set; }
    public ApplicationUser? ReviewerUser { get; set; }

    public ICollection<PaStatusHistory> StatusHistory { get; set; } = [];
    public ICollection<PaDocument> Documents { get; set; } = [];
    public ICollection<PaComment> Comments { get; set; } = [];
    public ICollection<Notification> Notifications { get; set; } = [];
}
